### ISSUE TITLE
使用TbsBridgeWebView 空指针

### ISSUE THREAD

**Issue by tu0908** [hjhrq1991/JsBridge#3]
![Uploading image.png…]()
09-21 09:15:32.827 22578-23509/com.my.trip W/System.err: java.lang.NullPointerException
09-21 09:15:32.827 22578-23509/com.my.trip W/System.err:     at com.tencent.tbs.sdk.extension.s.o(Unknown Source)
09-21 09:15:32.827 22578-23509/com.my.trip W/System.err:     at com.tencent.tbs.sdk.extension.TbsSDKExtension.b(Unknown Source)
09-21 09:15:32.827 22578-23509/com.my.trip W/System.err:     at com.tencent.tbs.sdk.extension.TbsSDKExtension.a(Unknown Source)
09-21 09:15:32.827 22578-23509/com.my.trip W/System.err:     at com.tencent.tbs.sdk.extension.n.run(Unknown Source)
09-21 09:15:32.827 22578-23509/com.my.trip W/System.err:     at java.util.Timer$TimerImpl.run(Timer.java:284)
09-21 09:15:33.477 22578-23509/com.my.trip W/System.err: java.lang.NullPointerException
09-21 09:15:33.487 22578-23509/com.my.trip W/System.err:     at com.tencent.tbs.sdk.extension.s.o(Unknown Source)
09-21 09:15:33.487 22578-23509/com.my.trip W/System.err:     at com.tencent.tbs.sdk.extension.TbsSDKExtension.a(Unknown Source)
09-21 09:15:33.487 22578-23509/com.my.trip W/System.err:     at com.tencent.tbs.sdk.extension.TbsSDKExtension.b(Unknown Source)
09-21 09:15:33.487 22578-23509/com.my.trip W/System.err:     at com.tencent.tbs.sdk.extension.TbsSDKExtension.a(Unknown Source)
09-21 09:15:33.487 22578-23509/com.my.trip W/System.err:     at com.tencent.tbs.sdk.extension.n.run(Unknown Source)
09-21 09:15:33.487 22578-23509/com.my.trip W/System.err:     at java.util.Timer$TimerImpl.run(Timer.java:284)
09-21 09:15:34.077 22578-22578/com.my.trip W/Toast: From com.my.trip, go ahead.

**Comment by hjhrq1991** [comment]
请上传未混淆的错误日志，或把该日志进行mapping映射
